app/models/__init__.py
from app.models.users import User
from app.models.posts import Post

app/models/posts.py
from sqlalchemy import Column, Integer, String, Text, DateTime
from app import db
from datetime import *


class Post(db.Model):
    __tablename__ = 'post'
    id = Column(db.Integer, primary_key=True)
    title = Column(String(255), unique=True)
    body = Column(Text)
    created_at = Column(DateTime, index=True, default=datetime.utcnow)
    last_edit = Column(DateTime, index=True, onupdate=datetime.utcnow, default=datetime.utcnow)
    author_id = Column(Integer, db.ForeignKey('users.id'))
    user = db.relationship('User', backref='posts')

app/models/users.py
from sqlalchemy import Column, Integer, String
from flask_login import UserMixin
from app import login, db

class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(50), unique=True)
    password = Column(String(120), unique=True)
    role = Column(String(20))

    def __init__(self, username=None, password=None, role=None):
        self.username = username
        self.password = password
        self.role = role

    def __repr__(self):
        return self.username


    @login.user_loader
    def load_user(id):
        return User.query.get(int(id))


    def get_user(self):
        return {'id': self.id, 'username':self.username, 'password':self.password, 'role':self.role}

app/__init__.py
from flask import Flask
from flask_admin import Admin
import flask_sqlalchemy
import app.config as Configuration
from app.views import UserView, AdminView, PostView
from flask_admin.menu import MenuLink
from flask_login import LoginManager

'''
    Instantiare DB and Login Manager
'''
db = flask_sqlalchemy.SQLAlchemy()
login = LoginManager()


def create_app():

    """
        Create App
    """
    app = Flask(__name__)

    '''
        Init Database
    '''
    db.init_app(app)

    '''
        Init Login
    '''
    login.init_app(app)
    '''
        Configuring App
    '''
    Configuration.config(app)

    '''
        Administration interface
    '''
    from app.models import User, Post
    # Admin Left Side
    admin = Admin(app, index_view=AdminView(url='/admin'), template_mode='bootstrap3')
    admin.add_view(UserView(User, db.session))
    admin.add_view(PostView(Post, db.session))
    # Admin Right Side
    admin.add_link(MenuLink(name='Torna al sito publico', endpoint='public.public'))

    '''
        Add Blueprint Routes
    '''
    from app.routes import register_blueprints_routes
    register_blueprints_routes(app)

    '''
        Return Configured App
    '''
    return app

app/models/graph/__init__.py
from app.models.graph.Node import Node
from app.models.graph.Edge import Edge

app/routes/__init__.py
from app.routes.admin import admin_route
from app.routes.public import public_route
from app.routes.security import flask_security
from app.routes.handler import handler_route
from app.routes.graph.coverage import coverage_route
from flask import url_for, redirect



def register_blueprints_routes(app):
    app.register_blueprint(public_route)
    app.register_blueprint(flask_security)
    app.register_blueprint(handler_route)
    app.register_blueprint(coverage_route)

    '''
        Redirect '/' to '/public'
    '''
    @app.route('/')
    def index():
        return redirect(url_for('public.public'))

app/routes/admin.py
from flask import Blueprint, render_template, session,abort

admin_route = Blueprint('admin',__name__)

app/routes/handler.py
from flask import Blueprint, render_template, redirect,url_for

handler_route = Blueprint('handler_route',__name__)

@handler_route.app_errorhandler(404)
def page_not_found(error):
    # note that we set the 404 status explicitly
    return render_template('utils/404.html'), 404


@handler_route.app_errorhandler(403)
def page_not_found(error):
    # note that we set the 404 status explicitly
    return redirect(url_for('flask_security.login'))

app/routes/public.py
from flask import Blueprint, render_template, session,abort
from app.models import Post

public_route = Blueprint('public',__name__, url_prefix='/public')


@public_route.route('/')
def public():
    posts = Post.query.order_by(Post.last_edit.desc()).all()
    return render_template('public/index.html', posts=posts)

app/routes/security.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_user
from app.models import User
from app.src.security import LoginForm


flask_security = Blueprint('flask_security', __name__, template_folder='templates')


@flask_security.route('/signin/', methods=['POST'])
def signin():

    form = LoginForm(request.form)

    username = form.username.data
    password = form.password.data

    if not validate_input(username,password):
        flash('Invalid username or password')
        return jsonify(check_error=''), 400

    user = User.query.filter_by(username=username, password=password).first()
    print(user.role)
    if user is None:
        flash('Invalid username or password')
        return jsonify(check_error='LOGIN_KO'), 401
    if user.role == 'ADMIN':
        login_user(user)
        return jsonify(check_error='OK')

    return jsonify(check_error='LOGIN_KO'), 401



@flask_security.route('/login/', methods=['GET', 'POST'])
def login():
    return render_template('public/index.html', login='LOGIN')


@flask_security.route('/logout/', methods=['GET', 'POST'])
def logout():
    return render_template('security/login.html', check_error='SESSION_EXPIRED')


def validate_input(username, password):
    if (username==None or username=='' or len(username)>20) or (password==None or password==''):
        return False
    else:
        return True

app/src/security/__init__.py
from app.src.security.LoginForm import LoginForm

app/views/AdminView.py
from flask_admin import BaseView, AdminIndexView, expose
from flask_login import current_user


class AdminView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated

    @expose('/')
    def index(self):
        return self.render('/admin/index.html')

    @expose('/post')
    def post(self):
        return self.render('/admin/post.html')

app/views/PostView.py
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user

class PostView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated

app/views/UserView.py
from flask_admin.contrib.sqla import ModelView
from flask_login import current_user
from flask_admin import expose

class UserView(ModelView):
    def is_accessible(self):
        return current_user.is_authenticated

app/views/__init__.py
from app.views.AdminView import AdminView
from app.views.UserView import UserView
from app.views.PostView import PostView

app/templates/base/admin_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AlgoRizzi</title>


</head>
<body style="padding-top: 4px;">

{% include 'admin/master.html' %}

{% block header %} {% endblock %}

{% block body %}
    <div class="container">
         <div class="row">
            <div class="column content">
                {% block content %} {% endblock %}
            </div>
         </div>
    </div>
{% endblock %}

app/templates/base/exercises_template.html
{% extends 'base/public_template.html' %}

{% block content %}

    <!-- Description accordion -->
    <div class="card shadow mb-4" style="margin-left: 5px; margin-right: 5px;">
        <a role="button" href="#exDescription" class="card-header py-3" data-toggle="collapse" data-target="#exDescription" aria-expanded="false" aria-controls="exDescription">
          <h6 class="m-0 font-weight-bold text-primary">
            Description
          </h6>
        </a>
        <div id="exDescription" class="collapse">
            <div  class="card-body">
                {% block description %} {% endblock %}
            </div>
        </div>
    </div>

    <!-- Content section -->
    <div class="card shadow mb-4" style="margin-left: 5px; margin-right: 5px;">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">
              {% block card_title %} {% endblock %}
          </h6>
        </div>
        <div class="card-body">
            {% block card_content %} {% endblock %}
        </div>
    </div>


{% endblock %}

app/templates/base/footer.html
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

app/templates/base/navbar.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">


    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="javascript:void(0);" id="idLogin">
          <i class="fas fa-2x fa-user-circle fa-sm fa-fw mr-2 text-gray-400"></i>
      </a>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

app/templates/base/public_template.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>AlgoRizzi</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/common.css') }}" rel="stylesheet">

  <!-- Vis.js -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.css" type="text/css" />
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis-network.min.js"> </script>

  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    {% block header %} {% endblock %}
</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">
      {% block wrapper %}
          {% block sidebar %}
                {% include 'base/side_bar.html' %}
          {% endblock %}

          {% block main %}
                <!-- Content Wrapper -->
                <div id="content-wrapper" class="d-flex flex-column">
                    <!-- Main Content -->
                    <div id="content">
                        {% include 'base/navbar.html' %}

                        <!-- Begin Page Content -->
                        <div class="container-fluid">
                            {% block content %} {% endblock %}
                        </div>
                    </div>
                    {% include 'base/footer.html' %}

                    <!-- End of Main Content -->
                </div>
                <!-- End of Content Wrapper -->
          {% endblock %}
      {% endblock %}
  </div>

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>


  {%  include 'security/loginModal.html' %}

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

  <!-- Page level plugins -->
  <script src="{{ url_for('static', filename='vendor/chart.js/Chart.min.js') }}"></script>


</body>

</html>

app/templates/base/side_bar.html
{% block left_sidebar %}

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">AlgoRizzi <sup>1.0</sup></div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">


      <!-- Heading -->
      <div class="sidebar-heading">
        Problems
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseGraph" aria-expanded="true" aria-controls="collapseGraph">
          <i class="fas fa-fw fa-folder"></i>
          <span>Graph</span>
        </a>
        <div id="collapseGraph" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Copertura:</h6>
            <a class="collapse-item" href="/public/coverage/">Copertura Archi</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Ricerca:</h6>
            <a class="collapse-item" href="#">Percorso minimo</a>
            <a class="collapse-item" href="#">Minor Costo</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseMatrix" aria-expanded="true" aria-controls="collapseMatrix">
          <i class="fas fa-fw fa-folder"></i>
          <span>Matrix</span>
        </a>
        <div id="collapseMatrix" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">First Group</h6>
            <a class="collapse-item" href="#">Matrix1</a>
            <a class="collapse-item" href="#">Matrix2</a>
            <a class="collapse-item" href="#">Matrix3</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Second Group:</h6>
            <a class="collapse-item" href="#">Matrix4</a>
            <a class="collapse-item" href="#">Matrix5</a>
          </div>
        </div>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

{% endblock %}

app/templates/index.html
{% include 'public/index.html' %}

app/templates/security/login.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/common.css') }}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-8 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user" method="post">
                    <div class="form-group">
                        {{ form.username(id='user', class="form-control form-control-user", placeholder="Insert Username...") }}
                    </div>
                    <div class="form-group">
                       {{ form.password(id='pwd', class="form-control form-control-user", placeholder="Insert Password...") }}
                    </div>
                    <div class="form-group">
                        {% if not current_user.is_authenticated and check_error=='LOGIN_KO' %}
                            <script>
                                document.getElementById("user").className="form-control form-control-user form-control-error";
                                document.getElementById("pwd").className="form-control form-control-user form-control-error";
                            </script>
                            {% with messages = get_flashed_messages() %}
                               {% if messages %}
                                 <ul class="flashes">
                                    {% for message in messages %}
                                     <div class="message_flash">{{ message }}</div>
                                    {% endfor %}
                                </ul>
                              {% endif %}
                             {% endwith %}
                        {% endif %}
                    </div>
                    <button class="btn btn-primary btn-user btn-block" type="submit">Login</button>
                    <hr>
                  </form>
                  <div class="text-center">
                    <a class="small" href="/">Torna al sito pubblico!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

</body>

</html>

app/templates/security/loginModal.html
<div id="idLoginModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Login</h4>
          <button id="idCloseModal" type="button" class="close" data-dismiss="modal">&times;</button>

        </div>
        <div class="modal-body">
          <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-12 col-lg-8 col-md-9">

          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <div class="user" >
                    <div class="form-group">
                        <input type="username" class="form-control form-control-user" id="idUsername" aria-describedby="emailHelp" placeholder="Enter Email Address..." required autofocus>
                    </div>
                    <div class="form-group">
                        <input type="password" class="form-control form-control-user" id="idPassword" placeholder="Password" required>
                    </div>

                    <div class="form-group">

                        <div id="idDataRequired" class="form-group" style="display: none;">
                            <ul class="flashes">
                                 <div class="message-flash-warning">Inserire Username e Password!</div>
                            </ul>
                        </div>
                        <div id="idAuthFailed" class="form-group" style="display: none;">
                            <ul class="flashes">
                                 <div class="message-flash-error">Username o Password errati!</div>
                            </ul>
                        </div>
                    </div>
                    <button id="idSubmit" class="btn btn-primary btn-user btn-block">Login</button>
                    <hr>
                  </div>
                  <div class="text-center">
                    <a class="small" href="/">Torna al sito pubblico!</a>
                  </div>
                </div>
              </div>
            </div>
        </div>

      </div>

    </div>

  </div>
      </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>

  </div>

  <!-- Login Modal Script -->
  {% include 'security/security_js.html' %}

app/templates/security/login_user.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Login</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-8 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <a href="/admin" class="btn btn-primary btn-user btn-block">
                      Login
                    </a>
                    <hr>
                  </form>
                  <div class="text-center">
                    <a class="small" href="/">Torna al sito pubblico!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

</body>

</html>

app/templates/security/security_js.html
<script>

    // Open Login Modal if get '/login'
    if ('{{ login }}' == 'LOGIN'){
        $("#idLoginModal").modal();
    }

    $(document).keydown(function(e){
        if (e.keyCode==13 && $('#idLoginModal').is('.show'))
            $('#idSubmit').click();
    });

    // Clear Login Field on Hidden Modal
    $( document ).ready(function() {

        $('#idLoginModal').on("hidden.bs.modal", function () {
            $('#idUsername').val("");
            $('#idPassword').val("");
            $("#idUsername").attr('class', 'form-control form-control-user');
            $("#idPassword").attr('class', 'form-control form-control-user');
            $("#idDataRequired").attr('style', 'display: none;')
            $("#idAuthFailed").attr('style', 'display: none;')
        });

        // Open Login Modal or redirect to 'admin' if already
        // authenticated when click avatar on top-right side
        $("#idLogin").click(function(){
            if ('{{ current_user.is_authenticated }}'=='True') {
                window.location.href = '{{ url_for("admin.index") }}'
            }
            else {
                $("#idLoginModal").modal();
            }
        });

        // Submit listener
        $('#idSubmit').click(function() {
            // Empty Fields
            if ($('#idUsername').val()=='' || $('#idPassword').val()=='' ) {
                $("#idUsername").attr('class', 'form-control form-control-user form-control-warning');
                $("#idPassword").attr('class', 'form-control form-control-user form-control-warning');
                $("#idDataRequired").attr('style', 'display: "";')
                $("#idAuthFailed").attr('style', 'display: none;')
            }
            else {
                $.ajax({
                    url: '/signin/',
                    type: "POST",
                    dataType: 'json',
                    data: {
                        username: $('#idUsername').val(),
                        password: $('#idPassword').val()
                    },
                    success: function (data) {
                        if (data['check_error']=='OK'){
                              window.location.href = '{{ url_for("admin.index") }}'
                        }
                    },
                    fail: function (data) {
                        console.log(data);
                    },
                    error: function (a) {
                        $("#idUsername").attr('class', 'form-control form-control-user form-control-error');
                        $("#idPassword").attr('class', 'form-control form-control-user form-control-error');
                        $("#idPassword").val("");
                        $("#idDataRequired").attr('style', 'display: none;')
                        $("#idAuthFailed").attr('style', 'display: "";')
                        console.log(a.responseJSON);
                    },
                })
            }
        });

    });


</script>

app/templates/utils/cards.html
<!-- Illustrations -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">
          {% block card_title %} {% endblock %}
      </h6>
    </div>
    <div class="card-body">
      <div class="text-center">
      </div>
        {% block card_content %} {% endblock %}
    </div>
</div>

app/templates/utils/cards_small.html
<!-- Earnings (Monthly) Card Example -->
<div class="col-xl-3 col-md-6 mb-4">
  <div class="card border-left-success shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        {% block card_small_content %} {% endblock %}
      </div>
    </div>
  </div>
</div>

app/templates/utils/search.html
<!-- Sidebar Toggle (Topbar) -->
<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
</button>

<!-- Topbar Search -->
<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
</form>